### ISSUE TITLE
ArgumentError 

### ISSUE THREAD

**Issue by ytuza** [autonomousvision/graf#1]
https://github.com/autonomousvision/graf/blob/eaa2d6e47e92a7f56f9531299b032c20c5b6caf6/submodules/nerf_pytorch/run_nerf.py#L368

The argument is duplicated, and causes an error
It should be 
parser.add_argument ("- N_rand", type = int, default = 32 * 32 * 4, help = 'batch size (number of random rays per gradient step)')

**Comment by katjaschwarz** [comment]
That's true, thanks! I fixed it in the file.
It should not cause an error in the main code though, as we only use the modified version of this file (run_nerf_mod.py). The other file is just included for completness of the submodule. Please refer to the original repo https://github.com/yenchenlin/nerf-pytorch for the latest version of the submodule.
