### ISSUE TITLE
Question about fine vs coarse raysampling

### ISSUE THREAD

**Issue by ebartrum** [autonomousvision/graf#10]
Hey, 
My impression from reading the paper was that the coarse then fine raysampling steps are performed on the same implicit function in order to sample in areas of higher alpha density for this function. However, my understanding from reading the code is that generator and generator fine have 2 separate implicit functions with different parameters.  Could you clarify which of these is correct? As far as I understand, only the output from generator fine is used to compute the loss.

**Comment by ebartrum** [comment]
Or is it that you only use the coarse ray sample, because in default.yaml N_importance is set to 0?

**Comment by katjaschwarz** [comment]
Yes, we only used coarse ray sampling to reduce the amount of required memory.
