### ISSUE TITLE
Question about training time and gpu

### ISSUE THREAD

**Issue by natureyoo** [autonomousvision/graf#11]
Thank you for your interesting works. 
I'm not familiar with this field, neural rendering, so I have no idea of the training time and required memory.
Could you let me know the training time and which GPU did you use for training?

**Comment by katjaschwarz** [comment]
We train on a single NVIDIA GEFORCE GTX 1080 Ti. Initial results can be observed after ~10 hours of training but for the results in the paper we trained for ~3 days.
