### ISSUE TITLE
quention about paper

### ISSUE THREAD

**Issue by diaodeyi** [autonomousvision/graf#12]
Hi，Thanks for your great work, can you explain for the detail about 'It is further important to note that we do not downsample the real image I based on s, but instead query I at sparse locations to retain high-frequency details, see Fig. 3.'?
As far as i am concerned, i think the bilinear sampling operation is just downsampling , but i down konw what exactly your means "query" in this sentence.

**Comment by diaodeyi** [comment]
By the way , even we konw the P(u, s) and how to use bilinear sampling operation on the real image i , to get the real patch?

**Comment by diaodeyi** [comment]
By the way , even we konw the v(u, s) and how to use bilinear sampling operation on the real image i , to get the real patch?
because the bilinear sampling operation is use four coordinate to calculate target one, now we have the  target one already.

And i don't think we have to calculate the coordinate according to  the v(u,s), we just need to ensure the patch's s is same?

**Comment by diaodeyi** [comment]
By the way, i don't think we have to calculate the coordinate according to the v(u,s), we just need to ensure the patch's s is same?

**Comment by katjaschwarz** [comment]
Sure, we sample patches instead of just downsampling the images. Simply downsampling the image would discard high-frequency information. Hence, we construct patches using dilation, which is shown in Figure 3.
