### ISSUE TITLE
There are many different categories and labels in a picture.

### ISSUE THREAD

**Issue by quan70636** [autonomousvision/graf#13]
This is a great project. I want to use giraffe to generate data of different shapes or specific conditions (such as darker scenes) from my dataset. But my custom dataset is very similar to COCO dataset. There are many different categories and labels in a picture. I also hope to be able to generate higher resolution images such as 640x640x3. Please suggest what I need to pay attention to.

**Comment by katjaschwarz** [comment]
Thank you. For giraffe, I cannot give you suggestions on this task though - I would suggest posting this question in [their repo](https://github.com/autonomousvision/giraffe) instead.
