### ISSUE TITLE
Question about the 150k chairs dataset from PhotoShapes

### ISSUE THREAD

**Issue by vishnukool** [autonomousvision/graf#3]
You mention you've used "150k Chairs from Photoshapes". Is there a script/generated images that you can share for this dataset to use? Thanks!

**Comment by yd-yin** [comment]
Hi! I have the same question. Could you please offer some information of `chairs` dataset, just like other datasets? Since working on all the data preprocessing, configs and training may be tedious for new comers.  
Thanks in advance!

**Comment by katjaschwarz** [comment]
Sorry, we are not planning on releasing the chair dataset. For a similar dataset please refer to: https://github.com/autonomousvision/giraffe
