### ISSUE TITLE
About input of network

### ISSUE THREAD

**Issue by WenjiaWang0312** [autonomousvision/graf#7]
I have a question. During evaluation, you network do not receive the input image. Maybe your method needs to train a model for every single object? How do you rotate the image without the knowledge of original image?

Thank you.

**Comment by WenjiaWang0312** [comment]
Anyone can help?

**Comment by katjaschwarz** [comment]
Our model does _not_ have an encoder. Therefore, we can only generate images from random noise but we cannot reconstruct a given image. In other words, we can generate a new image and control the camera pose for this new image, but we cannot reconstruct a given image and modify the camera pose there.

**Comment by WenjiaWang0312** [comment]
Thank you very much!
